-- AstraPay Capstone: Snowflake table creation and loading
-- Upload CSVs to an internal stage named @case_data_stage before running COPY INTO.

CREATE DATABASE IF NOT EXISTS BANKING_ENTERPRISE_CAPSTONE;
CREATE SCHEMA IF NOT EXISTS BANKING_ENTERPRISE_CAPSTONE.CASE_STUDY;
USE DATABASE BANKING_ENTERPRISE_CAPSTONE;
USE SCHEMA CASE_STUDY;

CREATE OR REPLACE FILE FORMAT CASE_CSV_FORMAT
  TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY='"' NULL_IF=('','NULL') TIMESTAMP_FORMAT='AUTO' DATE_FORMAT='AUTO';

CREATE OR REPLACE STAGE CASE_DATA_STAGE FILE_FORMAT = CASE_CSV_FORMAT;

CREATE OR REPLACE TABLE RAW_CUSTOMER(customer_id STRING, segment STRING, country STRING, onboarding_date DATE, kyc_status STRING);
CREATE OR REPLACE TABLE RAW_MERCHANT(merchant_id STRING, merchant_segment STRING, category STRING, country STRING, pricing_plan STRING, risk_tier STRING);
CREATE OR REPLACE TABLE RAW_TRANSACTION(transaction_id STRING, customer_id STRING, merchant_id STRING, amount NUMBER(18,2), currency STRING, channel STRING, status STRING, created_at TIMESTAMP_NTZ, route_id STRING);
CREATE OR REPLACE TABLE RAW_PAYMENT_EVENT(transaction_id STRING, event_type STRING, event_time TIMESTAMP_NTZ, ingestion_time TIMESTAMP_NTZ, processing_ms NUMBER);
CREATE OR REPLACE TABLE RAW_FRAUD_DECISION(transaction_id STRING, rule_id STRING, decision STRING, risk_score FLOAT, model_version STRING);
CREATE OR REPLACE TABLE RAW_SETTLEMENT(settlement_id STRING, transaction_id STRING, settlement_amount NUMBER(18,2), settlement_currency STRING, fee_amount NUMBER(18,2), settlement_status STRING, settlement_date DATE);
CREATE OR REPLACE TABLE RAW_FX_RATE(rate_date DATE, currency STRING, rate_to_usd FLOAT, rate_type STRING);
CREATE OR REPLACE TABLE RAW_ROUTE_COST(route_id STRING, provider STRING, region STRING, cost_date DATE, fixed_fee FLOAT, variable_fee_pct FLOAT);
CREATE OR REPLACE TABLE RAW_CHARGEBACK(chargeback_id STRING, transaction_id STRING, reason STRING, amount NUMBER(18,2), opened_at DATE, resolved_at DATE);
CREATE OR REPLACE TABLE RAW_MERCHANT_RISK_SNAPSHOT(merchant_id STRING, snapshot_month DATE, risk_score FLOAT, risk_band STRING);

-- Example COPY commands. Run after uploading the matching CSV files into @CASE_DATA_STAGE.
COPY INTO RAW_CUSTOMER FROM @CASE_DATA_STAGE/customer.csv FILE_FORMAT=(FORMAT_NAME=CASE_CSV_FORMAT);
COPY INTO RAW_MERCHANT FROM @CASE_DATA_STAGE/merchant.csv FILE_FORMAT=(FORMAT_NAME=CASE_CSV_FORMAT);
COPY INTO RAW_TRANSACTION FROM @CASE_DATA_STAGE/transaction.csv FILE_FORMAT=(FORMAT_NAME=CASE_CSV_FORMAT);
COPY INTO RAW_PAYMENT_EVENT FROM @CASE_DATA_STAGE/payment_event.csv FILE_FORMAT=(FORMAT_NAME=CASE_CSV_FORMAT);
COPY INTO RAW_FRAUD_DECISION FROM @CASE_DATA_STAGE/fraud_decision.csv FILE_FORMAT=(FORMAT_NAME=CASE_CSV_FORMAT);
COPY INTO RAW_SETTLEMENT FROM @CASE_DATA_STAGE/settlement.csv FILE_FORMAT=(FORMAT_NAME=CASE_CSV_FORMAT);
COPY INTO RAW_FX_RATE FROM @CASE_DATA_STAGE/fx_rate.csv FILE_FORMAT=(FORMAT_NAME=CASE_CSV_FORMAT);
COPY INTO RAW_ROUTE_COST FROM @CASE_DATA_STAGE/route_cost.csv FILE_FORMAT=(FORMAT_NAME=CASE_CSV_FORMAT);
COPY INTO RAW_CHARGEBACK FROM @CASE_DATA_STAGE/chargeback.csv FILE_FORMAT=(FORMAT_NAME=CASE_CSV_FORMAT);
COPY INTO RAW_MERCHANT_RISK_SNAPSHOT FROM @CASE_DATA_STAGE/merchant_risk_snapshot.csv FILE_FORMAT=(FORMAT_NAME=CASE_CSV_FORMAT);
